# Generated by Django 5.2 on 2025-04-05 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Anonymous", max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(default="student", max_length=50)),
                ("subscription", models.CharField(default="free", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GradeGarage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
                ("credits", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=100)),
                ("group_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("whatsapp", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("lecture_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("rating", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("rating", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PYQ",
            fields=[
                ("pyq_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
